<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{8149866d-6b51-42e4-8c43-383b4dff9c7c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fb_IotComm : FB_IotCommunicator := ( sHostName := 'broker.emqx.io',
										 nPort := 1883,
			 							 sMainTopic := 'cc_test',
			 							 sDeviceName := 'adrian_laptop',
			 							 sUser := 'asita',
			 							 sPassword := 'ccinc');
	mqtt_data : ST_Mqtt_Data;
	tmrSend : TON;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fb_IotComm.Execute(TRUE);

tmrSend(IN := NOT tmrSend.Q, PT := T#500MS);

IF fb_IotComm.bConnected AND tmrSend.Q THEN
	fb_IotComm.SendData(ADR(mqtt_data),SIZEOF(mqtt_data));
END_IF
			 
	]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="11" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="24" Count="0" />
      <LineId Id="23" Count="0" />
      <LineId Id="25" Count="1" />
      <LineId Id="12" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>