<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{8149866d-6b51-42e4-8c43-383b4dff9c7c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fb_IotComm : FB_IotCommunicator := ( sHostName := 'broker.emqx.io',
										 nPort := 1883,
			 							 sMainTopic := 'cc_test',
			 							 sDeviceName := 'adrian_laptop',
			 							 sUser := 'asita',
			 							 sPassword := 'ccinc');
	mqtt_data : ST_Mqtt_Data;
	tmrSend : TON;
	
	tmrCycleTime : TON;
	timeSP : REAL := 10;
	sp : REAL := 30;
	out : REAL;
	seconds : REAL := 1000;
	timePT : REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fb_IotComm.Execute(TRUE);

tmrSend(IN := NOT tmrSend.Q, PT := T#500MS);

IF fb_IotComm.bConnected AND tmrSend.Q THEN
	fb_IotComm.SendData(ADR(mqtt_data),SIZEOF(mqtt_data));
END_IF

timePT := timeSP * 	seconds;		 
tmrCycleTime(IN := NOT tmrCycleTime.Q,  PT := REAL_TO_TIME(timePT));
IF tmrCycleTime.Q THEN
	out := 0;
ELSE
//	out := out + sp * (UDINT_TO_LREAL(_TaskInfo[GETCURTASKINDEXEX()].CycleTime) / 10000000/timeSP);
	out := out + sp * (0.01/(timePT/seconds));
END_IF



	]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="11" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="24" Count="0" />
      <LineId Id="23" Count="0" />
      <LineId Id="25" Count="1" />
      <LineId Id="47" Count="0" />
      <LineId Id="12" Count="1" />
      <LineId Id="48" Count="1" />
      <LineId Id="51" Count="1" />
      <LineId Id="54" Count="0" />
      <LineId Id="50" Count="0" />
      <LineId Id="44" Count="1" />
      <LineId Id="43" Count="0" />
      <LineId Id="40" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>