<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{cc4f0746-d0f9-4454-8a3d-2c3137eb714f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	cluster_control : FB_Cluster_Control();
	sita_out : REAL;
	sita_in1 : REAL;
	sita_in2 : REAL;
	sita_setout : FB_SetOutput_TwoInputs();
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[cluster_control();

//sita_out := F_SetOutput_LatestInput(in1 := TO_REAL(sita_in1),in2 := TO_REAL(sita_in2));


sita_setout(io_in1 := sita_in1,io_in2 := sita_in2, o_set_value => sita_out);]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="14" Count="1" />
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>