<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{cc4f0746-d0f9-4454-8a3d-2c3137eb714f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	cluster_control : FB_Cluster_Control();
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[cluster_control();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>