<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_RateOfChange" Id="{617e06a5-72f1-4ce4-9bce-e18efc713518}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RateOfChange
VAR_INPUT
	i_value : REAL;
	io_reset : BOOL;
END_VAR
VAR_OUTPUT
	o_change_value : REAL;
	o_change_rate : REAL;
END_VAR
VAR_IN_OUT
//	io_reset : BOOL;
END_VAR
VAR
	value_reset : REAL;   // value at reset 

	tmr_Reset : TON := ( PT := T#24H);
	time_since_reset : REAL;  // seconds
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// 600 minute timer to get the total 
tmr_Reset(IN := NOT io_reset);

time_since_reset := TO_REAL( tmr_Reset.ET) / 1000;



IF io_reset THEN
	value_reset := i_value;
	o_change_rate := 0;
	o_change_value := 0;
//	io_reset := FALSE;
ELSIF time_since_reset > 0 THEN
	o_change_value := i_value - value_reset;
	o_change_rate := o_change_value / time_since_reset;
END_IF]]></ST>
    </Implementation>
    <LineIds Name="FB_RateOfChange">
      <LineId Id="18" Count="10" />
      <LineId Id="35" Count="0" />
      <LineId Id="29" Count="2" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>