<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{5694769d-e5b0-4b4f-a601-0c181f66d836}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Fan_Enable AT %Q* : BOOL;
	fan_counts AT %I* : UDINT;
	fan_rpm : REAL;
	tmr_fan_rpm : TON;
	counts_prev : UDINT;
	count_curr	: UDINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[tmr_fan_rpm( IN := NOT tmr_fan_rpm.Q, PT := T#1S);

IF tmr_fan_rpm.Q THEN
	count_curr := fan_counts;
	fan_rpm := TO_REAL(((count_curr - counts_prev)/2)*60);
	counts_prev := count_curr; 
END_IF]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="16" Count="1" />
      <LineId Id="12" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>