<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{e3df6719-4951-4784-9eb8-a54175815cd8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
	AI1 AT %I* : INT;
	AIs AT %I* : MDP5001_300_EE3A5F5D;
	AIsCh AT %I* : MDP5001_300_4B3D2459;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>