<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{7d2a8e06-aa46-4acf-877b-9ad0fe1d78e2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	eap_state AT %I* : UINT;
	pub_bytes  AT %Q* :  ARRAY[0..19] OF BYTE;
	sub_bools  AT %I* :  ARRAY[0..9] OF BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>