<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Service_IOs" Id="{db4b2c86-66d8-4aa5-8a6b-26c2bfdd0e13}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Service_IOs
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Service_IOs">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>