<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{29275dbf-fa6e-414e-9008-085e2326d27d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	warmup_sts : FB_State_IOs;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[warmup_sts();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>