<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{29275dbf-fa6e-414e-9008-085e2326d27d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

	out_warmup_state_sts 	AT %Q* 	: BYTE;
	out_activate_state_sts 	AT %Q* 	: BYTE;
	out_shutdown_state_sts 	AT %Q* 	: BYTE;
	out_error_sts			AT %Q*	: BOOL;
	out_error_code			AT %Q*	: DWORD;
	out_service1_sts		AT %Q*  : BYTE;
	out_service1_error_code AT %Q*	: DWORD;
	out_service2_sts		AT %Q*	: BYTE;
	out_service2_error_code AT %Q*	: DWORD;
	out_service3_sts		AT %Q*	: BYTE;
	out_service3_error_code AT %Q*	: DWORD;
	out_service4_sts		AT %Q*	: BYTE;
	out_service4_error_code AT %Q*	: DWORD;
	out_heartbeat			AT %Q* 	: BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>