<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Service_Dispatcher" Id="{a567eb61-ac7e-400e-a3c0-e91bb0f7a48e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Service_Dispatcher
VAR_INPUT
	i_service_req 		: ST_Util_Service_Req;
	i_shared_rs_count 	: UINT;
END_VAR
VAR_OUTPUT
	o_service_req					: BOOL;  // on/off request to utilities 
	o_assigned_rs_number	: ARRAY[1..2] OF UINT; // rs number that has been assigned to a service 
END_VAR
VAR
	service_req_queue	: ARRAY [1..rs_count] OF ST_Service_Assigned_Sts;
	idx_queue			: UINT;
	trig_service_assign		: R_TRIG;
	trig_service_release	: R_TRIG;
	
	service_assign				: BOOL;
	service_release				: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Add to queue 

FOR idx_queue := 1 TO rs_count DO
	IF (i_service_req.request_cmd = E_Util_Service_Req.On)  THEN 
		IF  (service_req_queue[idx_queue].rs_number = i_service_req.rs_number)  THEN
			service_assign := FALSE;
			EXIT;
		ELSE
			service_assign := TRUE;
		END_IF
	END_IF
END_FOR

FOR idx_queue := 1 TO rs_count DO
	IF (i_service_req.request_cmd = E_Util_Service_Req.Off)  THEN 
		IF  (service_req_queue[idx_queue].rs_number = i_service_req.rs_number)  THEN
			service_release := TRUE;
			EXIT;
		ELSE
			service_release := FALSE;
		END_IF
	END_IF
END_FOR


//trig_service_assign(CLK := i_service_req.request_cmd = E_Util_Service_Req.On);
//trig_service_release(CLK := i_service_req.request_cmd = E_Util_Service_Req.Off);

trig_service_assign(CLK := service_assign);
trig_service_release(CLK := service_release);

IF trig_service_assign.Q THEN
	FOR idx_queue := 1 TO rs_count DO
		IF service_req_queue[idx_queue].rs_number = i_service_req.rs_number THEN
			EXIT;
		ELSIF NOT service_req_queue[idx_queue].is_assigned AND  service_req_queue[idx_queue].rs_number <> i_service_req.rs_number   THEN 
			service_req_queue[idx_queue].is_assigned  := TRUE;
			service_req_queue[idx_queue].rs_number := i_service_req.rs_number;
			EXIT;
		END_IF
	END_FOR
END_IF

// Remove from queue
IF trig_service_release.Q THEN
	FOR idx_queue := 1 TO rs_count DO
		IF service_req_queue[idx_queue].rs_number =  i_service_req.rs_number THEN
			service_req_queue[idx_queue].rs_number := 0;
			service_req_queue[idx_queue].is_assigned  := FALSE;
			EXIT;
		END_IF
	END_FOR
END_IF

// Update queue
FOR idx_queue := 1 TO rs_count-1 DO
	IF  NOT service_req_queue[idx_queue].is_assigned  THEN 
		IF service_req_queue[idx_queue + 1].rs_number > 0 THEN 
			service_req_queue[idx_queue] := service_req_queue[idx_queue + 1];
			service_req_queue[idx_queue + 1].rs_number := 0;
			service_req_queue[idx_queue + 1].is_assigned := FALSE;
			
		END_IF
	END_IF
	IF idx_queue = 3 AND NOT service_req_queue[idx_queue].is_assigned THEN 
		EXIT;
	END_IF
END_FOR

// Service on/off requet to Utilities

o_service_req := service_req_queue[1].is_assigned ; // on request to utilities if queue pos #1 is populated / has a RS assigned 


// Service assigned sts to RS controller

IF i_shared_rs_count = 2 THEN
	FOR idx_queue := 1 TO i_shared_rs_count DO 
		IF service_req_queue[idx_queue].is_assigned THEN 
			o_assigned_rs_number[idx_queue] := service_req_queue[idx_queue].rs_number;
		ELSE
			o_assigned_rs_number[idx_queue] := 0;
		END_IF
	END_FOR
ELSIF i_shared_rs_count = 1 THEN
	IF service_req_queue[idx_queue].is_assigned THEN 
		o_assigned_rs_number[1] := service_req_queue[1].rs_number;
	ELSE
		o_assigned_rs_number[1] := 0;
	END_IF
END_IF


]]></ST>
    </Implementation>
    <Method Name="Clear_Queue" Id="{ec07c837-9081-45a3-91d1-67ce24451c4a}">
      <Declaration><![CDATA[METHOD Clear_Queue : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[FOR idx_queue := 1 TO rs_count DO
	service_req_queue[idx_queue].rs_number := 0;
	service_req_queue[idx_queue].is_assigned  := FALSE;
END_FOR]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Service_Dispatcher">
      <LineId Id="564" Count="92" />
      <LineId Id="60" Count="0" />
    </LineIds>
    <LineIds Name="FB_Service_Dispatcher.Clear_Queue">
      <LineId Id="6" Count="0" />
      <LineId Id="11" Count="1" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>