<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Utilities_Control" Id="{8c6b6cdd-7265-4a56-a4b4-c8746bfbe857}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Utilities_Control
VAR_INPUT
	i_init_utilities 		: BOOL;
	i_activate_util			: BOOL;
	i_shutdown_utilities 	: BOOL;
	i_fault_reset			: BOOL;
	
	i_state_req				: INT;
	
	i_cooling_pump_req		: ST_Util_Service_Req;
	i_deadair_pump_req		: ST_Util_Service_Req;
	i_steam_system_req		: ST_Util_Service_Req;
	i_purge_assist_req		: ST_Util_Service_Req;
END_VAR
VAR_OUTPUT
	o_util_error			: BOOL;
END_VAR
VAR
	in_bop_warmup_sts 		AT %I* : ST_SeqSts;
	in_bop_activate_sts		AT %I* : ST_SeqSts;
	in_bop_shutdown_sts		AT %I* : ST_SeqSts;
	in_bop_error_sts		AT %I* : BOOL;
	in_bop_error_code		AT %I* : DWORD;
	
	comms_fault		: BOOL;
	
	out_util_state_req 		AT %Q* : INT; // 0 = Idle, 1 = warmup, 2 = activavte, 3 = shutdown 
	out_util_reset_fault	AT %Q* : BOOL;
	
	
	
	cooling_pump	: FB_Utilities_Service;
	dead_air_pump	: FB_Utilities_Service;
	steam_sytem 	: FB_Utilities_Service;
	purge_assist 	: FB_Utilities_Service;
	
	//util_dispatcher	: FB_Utilities_Dispatcher;
	
	cooling_pump_dispatch : FB_Service_Dispatcher();
	deadair_pump_dispatch : FB_Service_Dispatcher();
	
	util_state : ( Idle := 0, Warmup := 1, Activate := 2, Shutdown := 3, Error) ;
	
	cooling_pump_req : ST_Util_Service_Req;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//util_dispatcher (i_cooling_pump_req := i_cooling_pump_req,  i_deadair_pump_req := i_deadair_pump_req);


// To make a FB_Util_Service_Control for shared and non-shared services 



//IF util_dispatcher.o_cooling_pump_assigned AND NOT cooling_pump.o_service_req_sts.faulted THEN 
//	cooling_pump.i_service_req.request_cmd := 1;
//ELSIF NOT  util_dispatcher.o_cooling_pump_assigned  THEN
//	cooling_pump.i_service_req.request_cmd := 2;
//ELSIF i_cooling_pump_req.request_cmd = 0 AND cooling_pump.o_service_req_sts.faulted THEN 
//	cooling_pump.i_service_req.request_cmd := 0;
//END_IF


]]></ST>
    </Implementation>
    <Property Name="CoolingPump_Assigned_RS" Id="{779fbffc-5bb8-48f2-a000-685aa64d8599}">
      <Declaration><![CDATA[PROPERTY CoolingPump_Assigned_RS : ARRAY[1..2] OF UINT;]]></Declaration>
      <Get Name="Get" Id="{0e27d998-d7ce-4e5d-b03a-a81813c6f904}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[CoolingPump_Assigned_RS := cooling_pump_dispatch.o_assigned_rs_number;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="CoolingPump_Control" Id="{87b36801-af68-47a8-9110-d4009490d768}">
      <Declaration><![CDATA[METHOD CoolingPump_Control : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// Clear Queue if pump is faulted from utilities controller
IF NOT cooling_pump.o_service_sts.faulted AND NOT comms_fault AND  HMI.util_auto_mode THEN 
	cooling_pump_req := i_cooling_pump_req;
ELSE
	cooling_pump_dispatch.Clear_Queue();
END_IF


// manage the cooling pump assignmnet queue based on request form reactor set controller
cooling_pump_dispatch( i_service_req := cooling_pump_req, i_shared_rs_count := 2);


IF hmi.util_auto_mode THEN 
	// set  the cooling pump on/off command based on dispacher assignnments
	IF cooling_pump_dispatch.o_service_req THEN 
		cooling_pump.i_service_req.request_cmd := E_Util_Service_Req.On;
	ELSE
		cooling_pump.i_service_req.request_cmd := E_Util_Service_Req.Off;
	END_IF	
ELSE
	cooling_pump.i_service_req.request_cmd := hmi.util_cooling_pump_cmd;
END_IF

IF ( i_cooling_pump_req.request_cmd = E_Util_Service_Req.Reset OR hmi.util_cooling_pump_cmd = E_Util_Service_Req.Reset) AND cooling_pump.o_service_sts.faulted THEN 
		cooling_pump.i_service_req.request_cmd := i_cooling_pump_req.request_cmd;
	END_IF

//  cooling pump ios ( cmd + sts )  mapping to/from utilities controller 
cooling_pump();
]]></ST>
      </Implementation>
    </Method>
    <Property Name="CoolingPump_Sts" Id="{7316fd9b-3061-4fa0-a714-ac480e11acfa}">
      <Declaration><![CDATA[PROPERTY CoolingPump_Sts : ST_Util_Service_Sts]]></Declaration>
      <Get Name="Get" Id="{d3c6616e-43cf-48e4-87e3-0a629123ca49}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[CoolingPump_Sts := cooling_pump.o_service_sts;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="DeadAirPump_Control" Id="{2dddd7cc-b65c-4e22-bf02-7de4b30df3b7}">
      <Declaration><![CDATA[METHOD DeadAirPump_Control : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
deadair_pump_dispatch( i_service_req := i_deadair_pump_req);
dead_air_pump();
]]></ST>
      </Implementation>
    </Method>
    <Property Name="DeadAirPump_Sts" Id="{f06135dc-afa2-4efa-8940-c4c64349210e}">
      <Declaration><![CDATA[PROPERTY DeadAirPump_Sts : ST_Util_Service_Sts]]></Declaration>
      <Get Name="Get" Id="{38a46abb-2a3d-4082-898e-ce5b5951812b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[DeadAirPump_Sts := dead_air_pump.o_service_sts;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="PurgeAssist_Sts" Id="{38bed4f6-0484-45ef-98fa-176288db34d8}">
      <Declaration><![CDATA[PROPERTY PurgeAssist_Sts : ST_Util_Service_Sts]]></Declaration>
      <Get Name="Get" Id="{77e09263-3af6-4d99-bf48-816409fdbc74}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[PurgeAssist_Sts := purge_assist.o_service_sts;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="State_Machine" Id="{098dda64-0e68-4a64-9b10-f955bc143fbc}">
      <Declaration><![CDATA[METHOD State_Machine : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF i_state_req = E_Util_State_Cmd.Shutdown THEN
	util_state := Shutdown;
END_IF

CASE util_state OF 
	
	Idle : 
		IF i_state_req = E_Util_State_Cmd.Warmup  AND NOT in_bop_error_sts THEN 
			util_state := Warmup;
		ELSIF 	in_bop_error_sts THEN 
			util_state := Error;
		END_IF
	Warmup: 
		out_util_state_req := Warmup;
		IF NOT in_bop_warmup_sts.error THEN 
			IF in_bop_warmup_sts.completed AND i_state_req = E_Util_State_Cmd.Activate THEN 
				util_state := Activate;
			END_IF
		ELSE
			util_state := Error;
		END_IF
	Activate: 
		out_util_state_req := Activate;
		IF  in_bop_activate_sts.error THEN 
			util_state := Error;
		END_IF
		
	Shutdown : 
		out_util_state_req := Shutdown;
		IF NOT in_bop_shutdown_sts.error THEN 
			IF in_bop_shutdown_sts.completed THEN 
				util_state := Idle;
			END_IF
		ELSE
			util_state := Error;
		END_IF
	Error: 
		IF i_fault_reset THEN 
			out_util_reset_fault := TRUE;
			IF NOT in_bop_error_sts THEN
				util_state := Idle;
			END_IF
		END_IF
		
END_CASE]]></ST>
      </Implementation>
    </Method>
    <Property Name="SteamSystem_Sts" Id="{67bbb3e4-1b43-46e6-b3ec-6650925c7d57}">
      <Declaration><![CDATA[PROPERTY SteamSystem_Sts : ST_Util_Service_Sts]]></Declaration>
      <Get Name="Get" Id="{3d1618d8-ce06-4106-9724-ecdc500e13d1}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[SteamSystem_Sts := steam_sytem.o_service_sts;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="FB_Utilities_Control">
      <LineId Id="374" Count="0" />
      <LineId Id="429" Count="2" />
      <LineId Id="416" Count="0" />
      <LineId Id="395" Count="8" />
      <LineId Id="406" Count="0" />
      <LineId Id="410" Count="0" />
      <LineId Id="142" Count="0" />
    </LineIds>
    <LineIds Name="FB_Utilities_Control.CoolingPump_Assigned_RS.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Utilities_Control.CoolingPump_Control">
      <LineId Id="6" Count="18" />
      <LineId Id="29" Count="2" />
      <LineId Id="39" Count="2" />
      <LineId Id="38" Count="0" />
      <LineId Id="32" Count="2" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Utilities_Control.CoolingPump_Sts.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Utilities_Control.DeadAirPump_Control">
      <LineId Id="6" Count="2" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Utilities_Control.DeadAirPump_Sts.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Utilities_Control.PurgeAssist_Sts.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Utilities_Control.State_Machine">
      <LineId Id="6" Count="43" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Utilities_Control.SteamSystem_Sts.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>