<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Utilities_Service" Id="{316b1915-9e3f-4dce-ae11-ef4ece4f6502}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Utilities_Service
VAR_INPUT
	i_service_req : ST_Util_Service_Req;
	
END_VAR
VAR_OUTPUT
	o_service_sts 	: ST_Util_Service_Sts;
END_VAR
VAR
	in_service_sts 			AT %I* : BYTE;
	in_service_error_code  	AT %I* : DWORD;
	
	out_service_req 		AT %Q* : BYTE;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[out_service_req := TO_BYTE(i_service_req.request_cmd);


o_service_sts.idle 				:= in_service_sts = E_Util_Service_Sts.PowerUp;
o_service_sts.ready 			:= in_service_sts = E_Util_Service_Sts.Active;
o_service_sts.running 			:= in_service_sts = E_Util_Service_Sts.Running;
o_service_sts.faulted 			:= in_service_sts = E_Util_Service_Sts.Faulted;
o_service_sts.error_code		:= in_service_error_code;



]]></ST>
    </Implementation>
    <LineIds Name="FB_Utilities_Service">
      <LineId Id="132" Count="10" />
      <LineId Id="25" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>