<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_LowestReal" Id="{06eaf0f5-fdf3-4de8-b4e4-1f9fb6ec5ab4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LowestReal : REAL
VAR_INPUT
	Value1																: REAL;
	Value2																: REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// F_LowestReal
// Rev 1.0 - March 14, 2024

F_LowestReal															:= SEL(Value1 < Value2, Value2, Value1);
]]></ST>
    </Implementation>
    <LineIds Name="F_LowestReal">
      <LineId Id="8" Count="3" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>