<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_Concat3" Id="{71fdf845-d37c-4549-a393-6d2b2e4ac56b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Concat3 : STRING
VAR_INPUT
	s1																	: STRING;
	s2																	: STRING;
	s3																	: STRING;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// F_Concat3
// Rev 1.0 - January 10, 2024

F_Concat3																:= CONCAT(s1, s2);
F_Concat3																:= CONCAT(F_Concat3, s3);
]]></ST>
    </Implementation>
    <LineIds Name="F_Concat3">
      <LineId Id="8" Count="2" />
      <LineId Id="7" Count="0" />
      <LineId Id="14" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>