<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_HighestInt" Id="{1eefb2dd-a801-40ca-83f4-983ff054a5e4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_HighestInt : INT
VAR_INPUT
	Value1																: INT;
	Value2																: INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// F_Highest2
// Rev 1.0 - March 14, 2024

F_HighestInt																:= SEL(Value1 > Value2, Value2, Value1);
]]></ST>
    </Implementation>
    <LineIds Name="F_HighestInt">
      <LineId Id="16" Count="2" />
      <LineId Id="8" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>