<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_LowestReal" Id="{9e88cf8b-2020-4575-a920-4afa8023f33d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_LowestReal : REAL
VAR_INPUT
	Value1																: REAL;
	Value2																: REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// F_LowerValue
// Rev 1.0 - March 14, 2024

F_LowestReal															:= SEL(Value1 < Value2, Value2, Value1);
]]></ST>
    </Implementation>
    <LineIds Name="F_LowestReal">
      <LineId Id="16" Count="2" />
      <LineId Id="8" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>