<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{a8abf07e-f80e-46ef-9d3e-44b28975408d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	eap_state AT %I* : UINT;
	sub_bytes  AT %I* :  ARRAY[0..19] OF BYTE;
	pub_bools  AT %Q* :  ARRAY[0..9] OF BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>