<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{ffecc0be-3ece-405c-bd0b-1ec36ceb0d51}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbWeatherStation : FB_WeatherStation;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbWeatherStation();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>