<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{f8f6236a-c53c-4d5d-bdf4-393a927affae}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	ecat_sim_device_state AT %I* : UINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>