<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{8c00b01f-f53f-430a-a974-d67c74f40a4b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bHalfSecondPulse													: BOOL;
	tonHalfSecPulse														: TON;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Theseus - Main
// Rev 1.0 - September 31, 2024

P_M01.plc_version														:= '24_12_03_00';

/// TIMER PULSE
IF tonHalfSecPulse.Q THEN
	bHalfSecondPulse													:= NOT bHalfSecondPulse;
	tonHalfSecPulse(IN:= FALSE);
END_IF
tonHalfSecPulse(IN:= TRUE, PT:= T#500MS);

P_U01();
P_M01();
P_Alarms();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="125" Count="4" />
      <LineId Id="134" Count="9" />
      <LineId Id="54" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>